# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bait' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'MBProgressHUD'
  pod 'JWTDecode', '~> 2.4'

  # Pods for bait

end
